# Generated by Django 4.2.4 on 2023-08-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
