# Generated by Django 4.2.4 on 2023-08-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights3', '0003_airport_alter_flight_destination_alter_flight_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
