# Generated by Django 4.2.4 on 2023-08-22 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights3', '0004_plane'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plane',
        ),
    ]
